import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import type { DocumentType, Locale } from "../types/document.types";
import { convertDocument, deleteDocument, duplicateDocument, safeDocuments } from "../store/documentStore";
import { money } from "../components/documents/DocumentPreview";
import { en } from "../locales/en";
import { es } from "../locales/es";
const slug=(l:Locale,t:DocumentType)=>l==="en"?t:({invoice:"factura",estimate:"estimado",proposal:"propuesta"}[t]);
export function DocumentsPage({locale}:{locale:Locale}){
 const t=locale==="en"?en:es,n=useNavigate(),[docs,setDocs]=useState(safeDocuments),[q,setQ]=useState(""),[f,setF]=useState("all");
 const tx=(a:string,b:string)=>locale==="en"?a:b,refresh=()=>setDocs(safeDocuments()),open=(id:string)=>`/${locale}/demo/${locale==="en"?"preview":"vista-previa"}/${id}`;
 const rows=docs.filter(d=>(f==="all"||d.documentType===f||d.status===f)&&`${d.documentNumber} ${d.client.name} ${d.client.company} ${d.business.businessName}`.toLowerCase().includes(q.toLowerCase()));
 const convert=(id:string)=>{if(confirm(tx("Create a new invoice from this document?","¿Crear una factura nueva desde este documento?"))){const x=convertDocument(id,"invoice");refresh();if(x)n(open(x.id))}};
 const remove=(id:string)=>{if(confirm(tx("Delete this document?","¿Eliminar este documento?"))){deleteDocument(id);refresh()}};
 return <section><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-black">{tx("Saved documents","Documentos guardados")}</h1><Link className="primary" to={`/${locale}/demo/${slug(locale,"invoice")}`}>{tx("New document","Nuevo documento")}</Link></div><div className="card mb-4 flex flex-wrap gap-3 p-4"><input className="rounded-lg border px-3 py-2" placeholder={tx("Search number, client or business","Buscar número, cliente o empresa")} value={q} onChange={e=>setQ(e.target.value)}/><select className="rounded-lg border px-3 py-2" value={f} onChange={e=>setF(e.target.value)}>{[["all",tx("All","Todos")],["invoice",tx("Invoices","Facturas")],["estimate",tx("Estimates","Estimados")],["proposal",tx("Proposals","Propuestas")],["draft",t.status.draft],["sent",t.status.sent],["paid",t.status.paid],["accepted",t.status.accepted]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="grid gap-3">{rows.map(d=><article key={d.id} className="card grid gap-3 p-4 lg:grid-cols-[1fr_1fr_110px_120px_1.5fr] lg:items-center"><div><small>{tx("Type / Number","Tipo / Número")}</small><br/><b>{t.documents[d.documentType]} · {d.documentNumber}</b></div><div><small>{tx("Client","Cliente")}</small><br/><b>{d.client.name||d.client.company||"—"}</b></div><div><small>Total</small><br/><b>{money(d.total,d.currency)}</b></div><div><small>{tx("Status","Estado")}</small><br/><b>{t.status[d.status==="partially-paid"?"partiallyPaid":d.status]}</b></div><div className="flex flex-wrap gap-2"><Link className="secondary text-xs" to={open(d.id)}>{tx("Open","Abrir")}</Link><button className="secondary text-xs" onClick={()=>n(`/${locale}/demo/${slug(locale,d.documentType)}?id=${d.id}`)}>{t.common.edit}</button><button className="secondary text-xs" onClick={()=>{duplicateDocument(d.id);refresh()}}>{tx("Duplicate","Duplicar")}</button>{d.documentType!=="invoice"&&<button className="secondary text-xs" onClick={()=>convert(d.id)}>{tx("Convert","Convertir")}</button>}<button className="text-xs font-bold text-rose-600" onClick={()=>remove(d.id)}>{t.common.delete}</button></div></article>)}{!rows.length&&<div className="card p-8 text-center text-slate-500">{tx("No documents found.","No se encontraron documentos.")}</div>}</div></section>
}
