import { useState } from "react";
import type { BusinessDocument, Locale } from "../../types/document.types";
import { calculateDocumentTotals } from "../../utils/calculations";
import { en, studio as studioEn } from "../../locales/en";
import { es, studio as studioEs } from "../../locales/es";
import { PremiumActions } from "./PremiumActions";
export function money(value:number,currency:string,locale:Locale="en"){return new Intl.NumberFormat(locale==="en"?"en-US":"es-ES",{style:"currency",currency}).format(value||0)}
const proposalLabels={en:["Cover","Executive Summary","Client Challenge","Proposed Solution","Scope of Work","Deliverables","Timeline","Investment","Terms","Acceptance"],es:["Portada","Resumen ejecutivo","Necesidad del cliente","Solución propuesta","Alcance de trabajo","Entregables","Cronograma","Inversión","Términos","Aceptación"]};
export function DocumentPreview({document,locale,showActions=true}:{document:BusinessDocument;locale:Locale;showActions?:boolean}){const [premium,setPremium]=useState(""),d=calculateDocumentTotals(document);if(d.documentType==="proposal")return <ProposalPreview document={d} locale={locale} premium={premium} setPremium={setPremium} showActions={showActions}/>;return <div>{showActions&&<PremiumActions document={d} locale={locale} onDesign={setPremium}/>} {d.documentType==="estimate"?<EstimatePreview document={d} locale={locale} premium={premium}/>:<InvoicePreview document={d} locale={locale} premium={premium}/>}</div>}
function Brand({d}:{d:BusinessDocument}){return <div className="studio-brand">{d.business.logoUrl?<img src={d.business.logoUrl}/>:<img src="/images/next-studio-logo.png"/>}<b>{d.business.businessName||"NEXT STUDIO"}</b><p>{[d.business.addressLine1,d.business.city,d.business.state,d.business.postalCode,d.business.phone,d.business.email,d.business.website].filter(Boolean).join(" · ")}</p></div>}
function InvoicePreview({document:d,locale,premium}:{document:BusinessDocument;locale:Locale;premium:string}){const t=locale==="en"?en:es,s=locale==="en"?studioEn:studioEs;return <article data-premium-document className={`document-page studio-invoice ${premium.toLowerCase().replaceAll(" ","-")}`}><header className="studio-header"><Brand d={d}/><div className="studio-title"><h1>{t.documents.invoice}</h1><b className="studio-number">{d.documentNumber}</b><p>{t.documents.issueDate}: {d.issueDate}</p><p>{t.documents.dueDate}: {d.dueDate}</p></div><div className="studio-due"><small>{s.totalDue}</small><strong>{money(d.balanceDue,d.currency,locale)}</strong><span>{d.currency}</span></div></header><section className="studio-client"><div><small>{s.billTo}</small><b>{d.client.name||d.client.company}</b><p>{[d.client.company,d.client.addressLine1,d.client.city,d.client.email,d.client.phone].filter(Boolean).join(" · ")}</p></div><div><small>{s.status}</small><b className={`studio-status status-${d.status}`}>{t.status[d.status==="partially-paid"?"partiallyPaid":d.status]}</b></div></section><LineItems d={d} locale={locale}/><Totals d={d} locale={locale}/><StudioFooter d={d} locale={locale}/></article>}
function EstimatePreview({document:d,locale,premium}:{document:BusinessDocument;locale:Locale;premium:string}){const t=locale==="en"?en:es,s=locale==="en"?studioEn:studioEs;return <article data-premium-document className={`document-page studio-estimate ${premium.toLowerCase().replaceAll(" ","-")}`}><header className="studio-header estimate-head"><Brand d={d}/><div className="studio-title"><h1>{t.documents.estimate}</h1><b className="studio-number">{d.documentNumber}</b><p>{s.validUntil}: {d.expirationDate}</p></div><div className="studio-due"><small>{s.estimatedInvestment}</small><strong>{money(d.total,d.currency,locale)}</strong><span>{d.currency}</span></div></header><section className="studio-summary"><small>{s.projectSummary}</small><h2>{d.client.company||d.client.name}</h2><p>{d.notes}</p></section><LineItems d={d} locale={locale}/><section className="studio-scope"><div><small>{s.scope}</small><p>{d.terms}</p></div><div><small>{s.optionalServices}</small><p>{d.paymentInstructions}</p></div></section><Totals d={d} locale={locale}/><StudioFooter d={d} locale={locale}/></article>}
function LineItems({d,locale}:{d:BusinessDocument;locale:Locale}){const t=locale==="en"?en:es,s=locale==="en"?studioEn:studioEs;return <table className="studio-table"><thead><tr><th>{t.documents.description}</th><th>{t.documents.quantity}</th><th>{s.unitPrice}</th><th>{t.documents.amount}</th></tr></thead><tbody>{d.items.map(item=><tr key={item.id}><td><b>{item.description||"—"}</b><span>{item.details}</span></td><td>{item.quantity}</td><td>{money(item.rate,d.currency,locale)}</td><td>{money(item.lineTotal,d.currency,locale)}</td></tr>)}</tbody></table>}
function Totals({d,locale}:{d:BusinessDocument;locale:Locale}){const t=locale==="en"?en:es;const rows=[[t.documents.subtotal,d.subtotal],[t.documents.discount,d.discountTotal],[t.documents.tax,d.taxTotal],[t.documents.shipping,d.shipping],[t.documents.amountPaid,d.amountPaid]];return <section className="studio-totals">{rows.filter(([,value])=>Number(value)>0||rows[0][0]===t.documents.subtotal).map(([label,value])=><p key={String(label)}><span>{label}</span><b>{money(Number(value),d.currency,locale)}</b></p>)}<div><span>{t.documents.balanceDue}</span><strong>{money(d.balanceDue,d.currency,locale)}</strong></div></section>}
function StudioFooter({d,locale}:{d:BusinessDocument;locale:Locale}){const t=locale==="en"?en:es,s=locale==="en"?studioEn:studioEs;return <footer className="studio-footer"><div><small>{t.documents.notes}</small><p>{d.notes}</p><small>{t.documents.terms}</small><p>{d.terms}</p></div><div className="studio-payment"><small>{s.paymentMethods}</small><p>{d.paymentInstructions||"—"}</p>{d.signatureName&&<><small>{s.authorized}</small><b>{d.signatureName}</b></>}</div><span>{d.documentNumber}</span></footer>}
function ProposalPreview({document:d,locale,premium,setPremium,showActions=true}:{document:BusinessDocument;locale:Locale;premium:string;setPremium:(v:string)=>void;showActions?:boolean}){const t=locale==="en"?en:es,s=locale==="en"?studioEn:studioEs,p=d.proposalContent,labels=proposalLabels[locale];const content=[p?.projectTitle||d.documentNumber,p?.executiveSummary||d.notes,p?.clientChallenge||d.client.company,p?.proposedSolution||d.notes,p?.scopeOfWork||d.terms,p?.deliverables||d.items.map(x=>x.description).join(" · "),p?.timeline||d.issueDate,money(d.total,d.currency,locale),d.terms,p?.acceptanceText||d.signatureName];return <div>{showActions&&<PremiumActions document={d} locale={locale} onDesign={setPremium}/>}<div data-premium-document className={`proposal-pages ${premium.toLowerCase().replaceAll(" ","-")}`}>{labels.map((label,index)=><article className="proposal-page" key={label}><Brand d={d}/><small>{String(index+1).padStart(2,"0")}</small><h1>{index===0?d.client.company||d.client.name:label}</h1><h2>{index===0?label:""}</h2><p>{content[index]}</p>{index===7&&<strong>{s.estimatedInvestment}: {content[index]}</strong>}{index===9&&<b>{s.authorized}: {d.signatureName}</b>}</article>)}</div></div>}
